run:
	cargo build --release
	# 运行裁剪
	rust-objcopy \
		--strip-all target/riscv64gc-unknown-none-elf/release/os \
		-O binary target/riscv64gc-unknown-none-elf/release/os.bin
	# 运行qemu
	qemu-system-riscv64 \
		-machine virt \
		-nographic \
		-bios ../bootloader/rustsbi-qemu.bin \
		-device loader,file=target/riscv64gc-unknown-none-elf/release/os.bin,addr=0x80200000
.PHONY: run