[package]
name = "user_lib"
version = "0.1.0"
edition = "2024"

[dependencies]
riscv = { git = "https://github.com/rcore-os/riscv", features = ["inline-asm"] }

[profile.release]
opt-level = 0
debug = true

[features]
test = []  # 空测试特性

[lib]
test = false